# Generated by Django 5.2.1 on 2025-06-26 18:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'uživatel',
                'verbose_name_plural': 'uživatelé',
            },
        ),
        migrations.CreateModel(
            name='Pojistenec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Pole smí obsahovat pouze písmena, mezery nebo pomlčky.', regex='^[A-Za-zÁČĎÉĚÍŇÓŘŠŤÚŮÝŽáčďéěíňóřšťúůýž\\s-]+$')])),
                ('prijmeni', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Pole smí obsahovat pouze písmena, mezery nebo pomlčky.', regex='^[A-Za-zÁČĎÉĚÍŇÓŘŠŤÚŮÝŽáčďéěíňóřšťúůýž\\s-]+$')])),
                ('email', models.EmailField(max_length=200, validators=[django.core.validators.EmailValidator()])),
                ('telefon', models.CharField(max_length=22, validators=[django.core.validators.RegexValidator(message='Zadejte platné telefonní číslo.', regex='^\\+?[\\d\\s]{9,20}$')])),
                ('ulice', models.CharField(max_length=200)),
                ('cislo', models.IntegerField()),
                ('mesto', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Pole smí obsahovat pouze písmena, mezery nebo pomlčky.', regex='^[A-Za-zÁČĎÉĚÍŇÓŘŠŤÚŮÝŽáčďéěíňóřšťúůýž\\s-]+$')])),
                ('psc', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Zadejte platné PSČ ve formátu 12345 nebo 123 45.', regex='^\\d{3}\\s?\\d{2}$')])),
            ],
            options={
                'verbose_name': 'Pojištěnec',
                'verbose_name_plural': 'Pojištěnci',
            },
        ),
        migrations.CreateModel(
            name='Pojisteni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=200)),
                ('castka', models.IntegerField()),
                ('predmet_pojisteni', models.CharField(max_length=200)),
                ('platnost_od', models.DateField()),
                ('platnost_do', models.DateField()),
                ('pojistenec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pojistenci.pojistenec')),
            ],
            options={
                'verbose_name': 'Pojištění',
                'verbose_name_plural': 'Pojištění',
            },
        ),
    ]
