# Generated by Django 5.2.1 on 2025-06-26 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojistenci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojistenec',
            name='email',
            field=models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='jmeno',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Pole smí obsahovat pouze písmena, mezery nebo pomlčky.', regex='^[A-Za-zÁČĎÉĚÍŇÓŘŠŤÚŮÝŽáčďéěíňóřšťúůýž\\s-]+$'), django.core.validators.MinLengthValidator]),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='mesto',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Pole smí obsahovat pouze písmena, čísla, mezery nebo pomlčky.', regex='^[A-Za-zÁČĎÉĚÍŇÓŘŠŤÚŮÝŽáčďéěíňóřšťúůýž0-9\\s-]+$'), django.core.validators.MinLengthValidator]),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='prijmeni',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Pole smí obsahovat pouze písmena, mezery nebo pomlčky.', regex='^[A-Za-zÁČĎÉĚÍŇÓŘŠŤÚŮÝŽáčďéěíňóřšťúůýž\\s-]+$'), django.core.validators.MinLengthValidator]),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='psc',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Zadejte platné PSČ ve formátu 12345 nebo 123 45.', regex='^\\d{3}\\s?\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='ulice',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Pole smí obsahovat pouze písmena, čísla, mezery nebo pomlčky.', regex='^[A-Za-zÁČĎÉĚÍŇÓŘŠŤÚŮÝŽáčďéěíňóřšťúůýž0-9\\s-]+$'), django.core.validators.MinLengthValidator]),
        ),
        migrations.AlterField(
            model_name='pojisteni',
            name='predmet_pojisteni',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Pole smí obsahovat pouze písmena, čísla, mezery nebo pomlčky.', regex='^[A-Za-zÁČĎÉĚÍŇÓŘŠŤÚŮÝŽáčďéěíňóřšťúůýž0-9\\s-]+$'), django.core.validators.MinLengthValidator]),
        ),
        migrations.AlterField(
            model_name='pojisteni',
            name='typ',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Pole smí obsahovat pouze písmena, čísla, mezery nebo pomlčky.', regex='^[A-Za-zÁČĎÉĚÍŇÓŘŠŤÚŮÝŽáčďéěíňóřšťúůýž0-9\\s-]+$'), django.core.validators.MinLengthValidator]),
        ),
    ]
